vue
SCUT-StudentUnion/Material pull request #5
Opened 2018-08-20 12:33 UTC by GoJam11

我发起了一个pull request

2018-08-20 12:41 UTC, huww98 requested changes
.DS_Store文件不应该check进存储库，把他删掉，并添加到gitignore文件里吧

docs文件夹是GitHub pages用的，你把它移走了GitHub pages就用不了了。

2018-08-20 13:01 UTC, huww98 requested changes
temp.html temp.js是什么鬼，不用的就删掉咯

你的缩进能不能统一一下呀

2018-08-20 13:01 UTC, huww98 commented on front-end/index.html
> +<DOCTYPE! html>
doctype不是这么写的吧。。

2018-08-20 13:01 UTC, huww98 commented on front-end/index.html
> +      <vtable v-for="item in todos" v-bind:a="item" vbind:key="item.id"></vtable>
vtable是啥标签？element ui的组件？

2018-08-20 13:06 UTC, GoJam11 commented on front-end/index.html
> +      <vtable v-for="item in todos" v-bind:a="item" vbind:key="item.id"></vtable>
对啊

2018-08-20 13:06 UTC, GoJam11 commented on front-end/index.html
> +<DOCTYPE! html>
明白了 嗯！

2018-08-21 06:22 UTC, GoJam11 commented
改好了！

2018-08-22 04:23 UTC, huww98 approved these changes

2018-08-22 04:27 UTC, merged